name: Update README
on:
  push:
    paths: ["emojis/**"]
    branches: [main]
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: python scripts/generate_emoji_table.py
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Update emoji table in README"
